swagger: "2.0"
info:
  title: Sample API Service
  description: Service for sample api
  version: ""
host: localhost:8002
consumes:
- application/json
- application/xml
- application/gob
produces:
- application/json
- application/xml
- application/gob
paths:
  /openapi.json:
    get:
      tags:
      - sampleApi
      summary: Download ./gen/http/openapi.json
      operationId: sampleApi#/openapi.json
      responses:
        "200":
          description: File downloaded
          schema:
            type: file
      schemes:
      - http
  /users/{id}:
    get:
      tags:
      - sampleApi
      summary: show sampleApi
      operationId: sampleApi#show
      parameters:
      - name: id
        in: path
        description: ID
        required: true
        type: integer
      responses:
        "200":
          description: OK response.
          schema:
            $ref: '#/definitions/SampleAPIShowResponseBody'
      schemes:
      - http
definitions:
  SampleAPIShowResponseBody:
    title: 'Mediatype identifier: user; view=default'
    type: object
    properties:
      email:
        type: string
        description: Email
        example: Dignissimos maiores autem molestias et laudantium voluptate.
      id:
        type: integer
        description: ID
        example: 8821557391028014726
        format: int64
      name:
        type: string
        description: Name
        example: Voluptas non rerum.
    description: ShowResponseBody result type (default view)
    example:
      email: Quo aut fuga architecto temporibus quas aut.
      id: 7155053564588095772
      name: Sint nostrum pariatur.
