# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a162de495ab1281cd4630fca6919d0296e1211928bf700abc020090156e7a4f538694b3dd519d9a436fdca3dc09c3635bfd883375fbac34c5ba5542bf571b9e8

test:
  secret_key_base: 0bd7d3b3ab03f4cabe620c27426a9401270df9ed7c99e4227d4f686cae0f931750578c603fddea682ee7a2e62a4c88148f8c2a03bcba094bfcf7ffa66cb7e2b5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
